# Site settings
title: Raio frontendizador!
email: raio.frontendizador@gmail.com
description: > 
  Raio frontendizador! Blog sobre desenvolvimento front end.
  HTML, CSS, Javascript, por Jota Teles.
baseurl: ""
url: "http://www.jotateles.com.br"
twitter_username: raiofront
github_username:  teles
author_name: Jota Teles
facebook_username: jota.teles
# Build settings
markdown: kramdown
