# Site settings
title: Interface e usabilidade
email: elisabetdemarco@gmail.com
description: > 
  Anchor Pixel - Blog sobre Usabilidade, Interface, Pesquisa, Antropologia e metodologias de trabalho.
baseurl: ""
url: "http://www.anchorpixel.com.br"
twitter_username: 
github_username:  elisabetdm
author_name: Elisabet De Marco
facebook_username: 

# ids for third party scripts
hotjar_id: 104255
google_analytics_id: UA-32369457-1
disqus_shortname: elisabetdm

# Build settings
markdown: kramdown
paginate: 4
paginate_path: "/pagina/:num/"
exclude:
  - 'bower_components/**/*'
  - 'node_modules/**/*'
  - 'README.md'
  - 'bower.json'
  - 'package.json'
  - 'Gruntfile.js'
  - 'Gulpfile.js'
  - 'tasks'
