# Site settings
title: Interface e usabilidade
email: elisabetdemarco@gmail.com
description: > 
  You need UX - Blog sobre Design centrado no usuário, Interface, Pesquisa e metodologias de trabalho.
baseurl: ""
url: "https://elisabetdm.github.io"
twitter_username: 
github_username:  elisabetdm
author_name: Elisabet De Marco
facebook_username: elisabet.demarco

# ids for third party scripts
hotjar_id: 104255
google_analytics_id: UA-32369457-1
disqus_shortname: elisabetdm

# Build settings
markdown: kramdown
paginate: 4
paginate_path: "/pagina/:num/"
exclude:
  - 'bower_components/**/*'
  - 'node_modules/**/*'
  - 'README.md'
  - 'bower.json'
  - 'package.json'
  - 'Gruntfile.js'
  - 'Gulpfile.js'
  - 'tasks'
